site_name: lernOS Template Leitfaden
site_url: https://cogneon.github.io/
docs_dir: src
site_dir: ../docs/de

nav:
    - Willkommen: index.md
    - Lernpfad: 
      - Organisiert euch (Woche 0): 2-00-Organisiert-euch.md
      - Mein „Why“, meine Themen und mein gesellschaftliches Engagement (Woche 1): 2-01-Mein-Why-meine-Themen-mein-Engagement.md
      - In welchem Bereich möchte ich aktiv werden? (Woche 2): 2-02-In-welchem-Bereich-moechte-ich-aktiv-werden.md
      - Zukünfte meines Engagements (Woche 3): 2-03-Zukuenfte-meines-Engagements.md
      - Darüber sprechen (Woche 4): 2-04-Darueber-sprechen.md
      - Meine Ressourcen (Woche 5): 2-05-Meine-Ressourcen.md
      - Art meines Engagements konkretisieren (Woche 6): 2-06-Art-meines-Engagements-konkretisieren.md
      - Maßnahmen, Aufgabe und Ziele ableiten (Woche 7): 2-07-Vorhaben.md
      - Es ist soweit. Ins Tun gekommen? (Woche 8): 2-08-Es-ist-soweit.md
      - 100 Tage - meine Zeit! (Woche 9): 2-09-100-Tage-Meine-Zeit.md
      - Wiedersehen nach 100 Tagen (Woche 10): 2-10–Wiedersehen-nach-100-Tagen.md
    - Download:
      - PDF-Version: https://github.com/cogneon/lernos-template/blob/master/de/build/lernos-engagement-guide.pdf
      - Word-Version: https://github.com/cogneon/lernos-template/blob/master/de/build/lernos-engagement-guide.docx
      - HTML-Version: https://github.com/cogneon/lernos-template/blob/master/de/build/lernos-engagement-guide.html
      - E-Book (epub): https://github.com/cogneon/lernos-template/blob/master/de/build/lernos-engagement-guide.epub
      - E-Book (mobi): https://github.com/cogneon/lernos-template/blob/master/de/build/lernos-engagement-guide.mobi
    - Links:
      - lernos.org: https://lernos.org
      - CONNECT Community: https://community.cogneon.de

theme:
    name: 'material'
    custom_dir: src/overrides
    palette:
        scheme: lernos
    language: de
    icon:
      logo: material/home
      repo: fontawesome/brands/github

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/matomo.js

repo_name: 'cogneon/lernos-template'
repo_url: 'https://github.com/cogneon/lernos-template'

extra:
    social:
        - icon: fontawesome/brands/mastodon
          link: 'https://colearn.social/@lernos'
        - icon: fontawesome/brands/linkedin
          link: 'https://www.linkedin.com/showcase/lern-os'
        - icon: fontawesome/brands/github
          link: 'https://github.com/cogneon'
    giscus: true
    generator: false

copyright: cogneon.de/impressum

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - rss:
      abstract_chars_count: -1  # -1 for full content